server:
http_listen_port: 9080
grpc_listen_port: 0
positions:
filename: /data/promtail/positions.yaml
clients:
- url: http://{{inventory_hostname}}:3100/loki/api/v1/push
scrape_configs:
# Local machine logs
- job_name: system
static_configs:
- targets:
    - localhost
    labels:
    job: varlogs-mon-server # FE: varlogs-scfe, BE: varlogs-scbe, Gualdaticker: varlogs-gualda, SAAS: varlogs-saas
    __path__: /var/log/*log